## 제너레이터와 async/await

제너레이터는 **코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개**할 수 있는 특수 함수다.

1. 제너레이터는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
    일반함수를 호출하면 제어권이 함수에게 넘어가고 함수 코드를 일괄 실행한다.
    즉, 함수 호출자는 함수를 호출한 이후 함수 실행을 제어할 수 없다.
    제너레이터는 가능. 함수의 제어권을 함수가 독점하는 것이 아니라 함수 호출자에게 양도할 수 있다는 것을 의미한다.

2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
    일반함수에선 매개변수를 통해 함수 외부에서 값을 주입받고 함수를 일괄 실행해 결과값을 함수 외부로 반환한다.
    제너레이터는 함수 호출자와 양방향으로 상태를 주고받을 수 있다.
    제너레이터는 함수 호출자에게 상태를 전달할 수 있고 호출자로부터 상태를 전달받을 수도 있다.

3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
    제너레이터는 함수 코드를 실행하는것이 아니라 이터러블이면서 동시에 이터레이터인 제너레이터 객체를 반환한다.


<br>

## 제너레이터 함수 정의

제너레이터 함수는 function* 키워드로 선언한다.

그리고 하나 이상의 yield 표현식을 포함한다.

이것을 제외하면 일반 함수를 정의하는 방법과 같다.

```js
//제너레이터 함수선언문
function* getDecFunc(){
    yield 1;
}

// 제너레이터 함수 표현식
const genExpFunc = function* () {
    yield 1;
}

// 제너레이터 메서드
const obj = {
    * genObjMethod() {
        yield 1
    }
}

// 제너레이터 클래스 메서드
class MyClass {
    * genClsMethod() {
        yield 1
    }
}

```


제너레이터 함수는 화살표 함수로 정의할 수 없다. !! 

또 new 연산자와 함께 생성자 함수로 호출할 수 없다.

<br>

## 제너레이터 객체

제너레이터 함수는 일반함수처럼 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다.

제너레이터 함수가 반환한 제너레이터 객체는 `이터러블` 이면서 `이터레이터`다.

```js
function* genFunc() {
    yield 1
    yield 2
    yield 3
}

const generator = genFunc()

console.log(Symbol.iterator in generator) //true
console.log('next' in generator) // true
```

제너레이터 객체는 next 메서드를 갖는 이터레이터지만 이터레이터에 없는 return, throw 메서드를 갖는다.

```js
function* genFunc(){
    try{
        yield 1
        yield 2
        yield 3
    } catch(e){
        console.error(e)
    }
}

const generator = genFunc()

console.log(generator.next()) // {value:1, done:false}
console.log(generator.return('End!')) // {value:'End!', done: true}

console.log(generator.throw('Error')) // {value: undefined, done:true} 

```

<br>

## 제너레이터의 일시 중지와 재개

yield 키워드, next 메서드를 통해 실행을 일시중지, 필요 시점에 재개할 수 있다.

일반 함수처럼 한번에 블록의 모든 코드를 일괄 실행하는것이 아니라 yield 표현식까지만 실행한다.

```js
function* genFunc(){
        yield 1
        yield 2
        yield 3
}

const generator = genFunc()

console.log(generator.next()) // {value:1, done:false}
// 처음 next 메서드를 호출하면 첫 yield까지 실행.
// 첫 yield 표현식에서 yield된 값 1이 할당된다.
// done 프로퍼티에는 제너레이터 함수가 끝까지 실행되었는지를 나타내는 false가 할당된다.

console.log(generator.next()) // {value:2, done:false}
console.log(generator.next()) // {value:3, done:false}
console.log(generator.next()) // {value:undefined, done:true}
```

이터레이터의 next 메서드와 달리 제너레이터 객체의 next 메서드에는 인수를 전달할 수 있다.

<img src="../../image/deepdive/generator.png" width="550">

<br>

## 제너레이터의 활용

#### 이터러블의 구현

이터레이션 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.

```js
const infiniteFibonacci = (function* () {
    let [pre, cur] = [0, 1]

    while(true){
        [pre, cur] = [cur, pre+cur]
        yield cur
    }
}())

for(const num of infiniteFibonacci){
    if(num > 10000) break
    console.log(num) // 1 2 3 5 8 ... 2584 4181 6765 
}
```

<br>

## 비동기 처리

프로미스의 후속 처리 메서드 then, catch, finally없이 비동기 처리 결과를 구현할 수 있다.



<br>

## async await

제너레이터로 비동기 처리를 동기 처리처럼 동작하도록
구현했지만 코드가 무척이나 장황하고 가독성도 나빠진다.

그리하여 awync/await이 도입됨.

프로미스의 then chath, finally 후속 처리 메서드에

콜백 함수를 전달해 비동기 처리 결과를 후속 처리할 필요 없이

마치 동기처럼 프로미스를 사용할 수 있다.

다시말해, 후속 처리 메서드 없이 동기 처리처럼

프로미스가 처리 결과를 반환하도록 구현할 수 있다.

```js
async function fetchTodo() {
    const url = 'https://jsonplaceholder.typicode.com/todos/1'

    const response = await fetch(url)
    const todo = await response.json()
    console.log(todo)
}

fetchTodo()

```

<br>

## async 함수

await은 반드시 async 함수 내부에서 사용.

언제나 프로미스를 반환한다.

프로미스를 반환하지 않더라도 암묵적으로 반환값을 resolve하는 프로미스를 반환한다.

```js
// async 함수 선언문
async function foo(n) { return n}
foo(1).then(v => console.log(v)) //1

// async 함수 표현식
const bar = async function(n) { return n}
bar(2).then( v => console.log(v)) //2

//async 화살표 함수
const baz = async n => n
baz(3).then(v => console.log(v))

// async 메서드
const obj = {
    async foo(n) {return n}
}
obj.foo(4).then(v => console.log(v))

//async 클래스 메서드
class MyClass {
    async bar(n) {return n}
}

const myClass = new MyClass()
myClass.bar(5).then(v => console.log(v)) //5

```

클래스의 constructor메서드는 async 메서드가 될 수 없다.
constructor는 인스턴스를 반환해야 하지만

async 함수는 언제나 프로미스를 반환해야하기 때문.

<br>

## await 키워드

프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다.

반드시 프로미스 앞에서 사용해야 한다.

```js
const getGithubUserName = async id => {
    const res = await fetch(`https://api.github.com/users/${id}`) //1
    const {name} = await res.json() //2
    console.log(name)
}

getGithubUserName('harry')
```

1의 fetch 함수가 수행한 HTTP 요청에 대한 서버의 응답이 도착해 fetch 함수가 반환한 프로미스가 settled 상태가 될때까지 1은 대기하게 된다.

이후 프로미스가 settled 상태가 되면 프로미스가 resolve한 처리결과가 res 변수에 할당된다.

이처럼 await 은 다음 실행을 일시 중지시켰다가
프로미스가 settled가 되면 다시 재개한다.

```js
async function foo() {
    const a = await new Promise(resolve => setTimeout(()=> resolve(1), 3000))
    const b = await new Promise(resolve => setTimeout(()=> resolve(2), 2000))
    const c = await new Promise(resolve => setTimeout(()=> resolve(3), 1000))

    console.log([a,b,c]) //[1,2,3]
}

foo() // 약 6초 걸림.
```

모든 프로미스에 await 사용을 주의한다.

첫번째 3초, 두번째 2초, 세번째 1초 소요.

그런데 foo 함수가 수행하는 3개의 비동기 처리는 서로 연관이 없어 개별적으로 수행되는 비동기 처리이므로 앞선

앞선 비동기 처리가 완료될 때까지 대기해서 순차적으로

처리할 필요가 없다.

따라서 아래처럼 처리한다.

```js
async function foo() {
    const res = await Promise.all([
        new Promise(resolve => setTimeout(()=> resolve(1), 3000)),
        new Promise(resolve => setTimeout(()=> resolve(2), 2000)),
        new Promise(resolve => setTimeout(()=> resolve(3), 1000))
    ])
    
    console.log(res) // [1,2,3]
}

foo() // 약 3초
```

다음의 bar 함수는 앞선 비동기 처리의 결과를 가지고 다음 비동기 처리를 수행해야한다. 따라서 비동기 처리의 처리 순서가 보장되어야 하므로 모든 프로미스에 await 키워드를 써서 순차처리 할 수밖에 없다.

```js
async function bar(n) {
     const a = await new Promise(resolve => setTimeout(()=> resolve(n), 3000))
    const b = await new Promise(resolve => setTimeout(()=> resolve(a+1), 2000))
    const c = await new Promise(resolve => setTimeout(()=> resolve(b+1), 1000))

    console.log([a,b,c]) //[1,2,3]
}

bar(1)

```

<br>

## 에러 처리

비동기 처리를 위한 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것.

에러는 호출자 방향으로 전파된다.

즉, 콜 스택의 아래 방향인 실행 컨텍스트가 푸시되기 직전에

푸시된 실행 컨텍스트 방향으로 전파된다.

하지만 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기 때문에 try...catch문을 사용해 에러를 캐치할 수 없다.

```js
try {
    setTimeout(()=> { throw new Error('Error!')}, 1000)
}catch(e) {
    console.error('캐치한 에러', e) //캐치 못함.
}

```

**async/await에서 에러 처리는 try...catch문을 사용할 수 있다.**

콜백 함수를 인수로 전달받는 비동기 함수와는 달리

프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확하다.

```js
const foo = async() => {
    try{
        const wrongUrl = 'httpsfdsafdsa'

        const response = await fetch(wrongUrl)
        const data = await response.json()
        console.log(data)
    }catch (err){
        console.error(err) // TypeError:failed to fetch
    }
}

foo()
```

HTTP 통신에서 발생한 네트워크 에러뿐 아니라 try코드 블록 내의 모든 문에서 발생한 일반적인 에러까지 모두 캐치할 수 있다.

async 함수 내에서 catch문을 사용해 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject하는

프로미스를 반환한다.

따라서 async 함수를 호출하고 Promise.prototype.catch 후속 처리 메서드를 사용해 에러를 캐치할 수도 있다.

```js
const foo = async () => {
    const wrongUrl = 'https:dfa'

    const response = await fetch(wrongUrl)
    const data = await response.json()
    return data
}

foo()
.then(console.log)
.catch(console.error) // TypeError

```

